### ISSUE TITLE
How to import d3-selection-multi along with default d3 bundle?

### ISSUE THREAD

**Issue by zzx88991** [d3/d3-selection-multi#10]
Hi, i am using SystemJS to import and load modules with minified js in the library folder(not using npm):
```
/libs/d3/d3.v4.min.js
/libs/d3/d3-selection-multi.v1.min.js
```

Here is my config

```
{
    packages: {
        'd3': {
            main: './d3.v4.min',
            defaultExtension: 'js',
            map: {
                    './multi-select': './d3-selection-multi.v1.min.js'
            }
       }
    }
}
```

Loading the packages:
```
import * as d3 from 'd3';
import 'd3/multi-select';
```

However, this will give me 404 on 

```
.../d3-selection.js 
.../d3-transition.js
```

I checked the d3-selection-multi.js and found that tthat those two modules are the dependencies.

So, here are my two questions:
 
1. Isn't the default `d3` bundle providing d3-selection.js and d3-transition.js?

2. how can I make this thing work so that I can use the plugin methods in d3-selection-multi?

Thanks!

**Comment by mbostock** [comment]
Sorry, but I’m not familiar with SystemJS, so I can’t advise on how to configure it. If you’re loading the ES5 bundles generated by Rollup, there should be no reference to “d3-selection” or “d3-transition” as the code from those modules is inlined directly into the bundle. That said, if your goal is to use D3 in an ES2015+ environment, you probably want to load the ES2015 source which would mean the [module entry](https://github.com/d3/d3/blob/master/package.json#L20) defined in the package.json (rather than the [main entry](https://github.com/d3/d3/blob/master/package.json#L18) which points to the generated bundle). But it looks like you’re not using the package.json at all and just pointing directly to the generated bundles.

**Comment by zzx88991** [comment]
Thanks for answering my question. Actually I am using Typescript and transecompile the code back to ES5 with bundle script below.
`<script src="https://d3js.org/d3-selection-multi.v1.min.js"></script>`
Correct me if i am wrong. Since i am running my app in chrome, the minified script thinks it is running in a ES2015 environment, so it starts to look for the module references for `d3-selection` and `d3-transition`? That is why the error is produced?

**Comment by mbostock** [comment]
The minified script knows nothing about ES2015. It’s just using the standard [UMD boilerplate](https://github.com/umdjs/umd) generated by Rollup. Look at the source here:

https://d3js.org/d3-selection-multi.v1.js

In an AMD environment (*e.g.*, when using RequireJS), the minified script declares that it depends on d3-selection and d3-transition. In a CommonJS environment, d3-selection and d3-transition are require’d. Otherwise, it assumes that the `d3` global already contains the necessary d3-selection and d3-transition modules. My guess is that you are in an AMD environment.

**Comment by zzx88991** [comment]
That answers my question. Yeah, it is running in AMD. Thanks!

**Comment by zzx88991** [comment]
Sorry, but there is one thing I still couldn't figure out. Since i am loading both d3.v4.min.js and d3-selection-multi.v1.min.js in AMD environment, why is `d3-selection-multi.v1.min.js` still missing the `d3-selection` and `d3-transition` modules? Aren't they exported by d3.v4.min.js?

**Comment by mbostock** [comment]
The expectation when you are using AMD is that you load d3-selection and d3-transition separately, rather than using the d3 default bundle. All the D3 bundles are defined anonymously (the recommended best practice for UMD), so either you’d need to write a shim or whatever to configure your AMD environment to draw d3-selection and d3-transition from the loaded d3 bundle, or you should require the modules separately and it’ll work the normal way.

**Comment by zzx88991** [comment]
Now i understand. I appreciate your answer!
