### ISSUE TITLE
webpack not working?

### ISSUE THREAD

**Issue by pollen8** [d3/d3-selection-multi#15]
I am seeing the same issue as reported here:
https://github.com/d3/d3-selection-multi/issues/9

npm ls gives me:
```
─┬ d3@4.8.0
│ ├── d3-array@1.2.0
│ ├── d3-axis@1.0.6
│ ├── d3-brush@1.0.4
│ ├── d3-chord@1.0.4
│ ├── d3-collection@1.0.3
│ ├── d3-color@1.0.3
│ ├── d3-dispatch@1.0.3
│ ├── d3-drag@1.0.4
│ ├─┬ d3-dsv@1.0.5
│ │ ├── iconv-lite@0.4.15
│ │ └── rw@1.3.3
│ ├── d3-ease@1.0.3
│ ├── d3-force@1.0.6
│ ├── d3-format@1.2.0
│ ├── d3-geo@1.6.3
│ ├── d3-hierarchy@1.1.4
│ ├── d3-interpolate@1.1.4
│ ├── d3-path@1.0.5
│ ├── d3-polygon@1.0.3
│ ├── d3-quadtree@1.0.3
│ ├── d3-queue@3.0.5
│ ├── d3-random@1.0.3
│ ├─┬ d3-request@1.0.5
│ │ └── xmlhttprequest@1.8.0
│ ├── d3-scale@1.0.5
│ ├── d3-selection@1.0.5
│ ├── d3-shape@1.0.6
│ ├── d3-time@1.0.6
│ ├── d3-time-format@2.0.5
│ ├── d3-timer@1.0.5
│ ├── d3-transition@1.0.4
│ ├── d3-voronoi@1.1.2
│ └── d3-zoom@1.1.4
├── d3-selection-multi@1.0.1
```
Running your test from a node command line does indeed show that the attrs, styles etc functions have been added when doing:

```
var d3  = require("d3");
 require("d3-selection-multi")
d3.selection.prototype
````

```
Selection {
  constructor: [Function: Selection],
  select: [Function],
  selectAll: [Function],
  filter: [Function],
  data: [Function],
  enter: [Function],
  exit: [Function],
  merge: [Function],
  order: [Function],
  sort: [Function],
  call: [Function],
  nodes: [Function],
  node: [Function],
  size: [Function],
  empty: [Function],
  each: [Function],
  attr: [Function],
  style: [Function],
  property: [Function],
  classed: [Function],
  text: [Function],
  html: [Function],
  raise: [Function],
  lower: [Function],
  append: [Function],
  insert: [Function],
  remove: [Function],
  datum: [Function],
  on: [Function],
  dispatch: [Function],
  interrupt: [Function],
  transition: [Function],
  attrs: [Function],
  styles: [Function],
  properties: [Function] }
```

However using webpack, with the following js code does not work:
(file = /examples/examples.js)
``` javascript
var d3 = require('d3');
require('d3-selection-multi');
console.log(d3.selection.prototype);
```
in that attrs, and styles are not available in the d3 selection prototype object. 

Here's the webpack config I am using:

``` javascript
var webpack = require('webpack'),
  libraryName = 'cl-react-graph',
  path = require('path'),
  entry = [
    './examples/examples.js'
  ],
  plugins = [
    new webpack.NoEmitOnErrorsPlugin()
  ],
  loaders = [
    {test: /\.js$/, exclude: /(node_modules)/, loader: 'babel-loader'}
  ];

module.exports = {
  devtool: 'cheap-module-source-map',
  entry: entry,
  output: {
    path: path.join(__dirname, 'examples'),
    publicPath: '/',
    filename: 'index.js',
    library: libraryName,
    libraryTarget: 'umd',
    umdNamedDefine: true
  },
  module: {
    loaders: loaders
  },
  plugins: plugins,
  watchOptions: {
    poll: true
  },
  externals: [
    {
      react: {
        root: 'React',
        commonjs2: 'react',
        commonjs: 'react',
        amd: 'react'
      }
    },
    {
      'react-dom': {
        root: 'ReactDOM',
        commonjs2: 'react-dom',
        commonjs: 'react-dom',
        amd: 'react-dom'
      }
    }
  ]
};
```

**Comment by mbostock** [comment]
This typically occurs when Webpack is misconfigured to resolve `d3` as the generated UMD bundle ([build/d3.js](https://unpkg.com/d3/build/d3.js)) and not the ES modules ([index.js](https://github.com/d3/d3/blob/master/index.js)). As a result you end up with two copies of the d3-selection module, and d3-selection-multi defines *selection*.transition and related methods on an internal copy of d3-selection rather than the one exposed by d3.

To fix Webpack’s configuration, you probably need to set one of these:

* [resolve.packageMains](https://webpack.github.io/docs/configuration.html#resolve-packagemains)
* [resolve.mainFields](https://webpack.js.org/configuration/resolve/#resolve-mainfields)

In particular note that in Webpack 2 with the target `web`, Webpack prefers the `browser` entry point to the `module` entry point, which leads to the problem described above. I’m not sure why Webpack doesn’t prefer the `module` entry point instead, if it exists… but then maybe Webpack doesn’t provide ES module to UMD translation by default, like Rollup does?

At any rate, I don’t provide support for build systems besides Rollup; I only use Rollup and I lack the familiarity with other tool chains to provide helpful advice. Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by curran** [comment]
@pollen8 It may be useful to try this [D3 Custom Bundle with Webpack](https://bl.ocks.org/curran/3b0ab871cffe021aa972680c3f4f62d3) as a starting point, then try adding `d3-selection-multi`.

**Comment by mbostock** [comment]
@curran That avoids the problem described above by using the individual D3 modules (for example importing d3-selection instead of d3). That’s a viable workaround, but I believe it’s possible to continue to use the d3 default bundle as long as Webpack is configured to consume ES modules as input rather than the generated UMD bundle.

(You can also configure Webpack to consume the CommonJS bundle, [d3.node.js](https://unpkg.com/d3@4.8.0/build/d3.node.js), by using the [main entry point](https://github.com/d3/d3/blob/v4.8.0/package.json#L18) instead of the browser entry point.)

**Comment by pollen8** [comment]
thanks for the reply guys!
To summarize this works perfectly for me:

```javascript
import * as d3 from 'd3/build/d3.node';
import d3SelectMulti from 'd3-selection-multi';
console.log(d3.selection.prototype);
```

I've made a merge request to add this to the readme:
https://github.com/d3/d3-selection-multi/pull/16

**Comment by parvezk** [comment]
@pollen8 Thank you, was looking for this!
