### ISSUE TITLE
Use attrs(), styles(), properties() as getters

### ISSUE THREAD

**Issue by mindrones** [d3/d3-selection-multi#4]
I tried this module by hacking d3's index.js like this:

``` js
export {
  mouse,
  namespace,
  namespaces,
  select,
  selectAll,
  selection,
  touch,
  touches,
  event
} from "./d3-selection-multi/selection";
```

and bundling it with `rollup`: `.attrs()`, `.styles()`, `.properties()` work perfectly as setters but would it be possible to turn them to getters if used without arguments?

I'd use it to harvest all attributes/properties/styles from a certain selection, like this:

``` js
selection.selectAll('*')
.each(function() {
  console.log(this, d3.select(this).attrs());
  // should print the attributes object: {id: "id", class:"foo bar", ...}
})
```

I could produce a PR but I'm not sure if this is the intended behavior. Thanks!

**Comment by mbostock** [comment]
If you want to use this module, you just need to add this to your index.js:

``` js
import "d3-selection-multi";
```

However, you must make sure that the version of d3-selection-multi you’re using is compatible with the version of d3-selection you’re using. The latest d3-selection version is 0.7, and assuming you want that, you’ll need d3-selection-multi 0.2.10, which I just released. (If they’re not compatible, then d3-selection-multi uses its own internal version of d3-selection, and you’ll get duplicate code.)

Back to the issue at hand, I think returning maps is probably a bad idea because they would be expensive to compute. It might be reasonable for attributes, which are defined explicitly for each node, but it would be a very large set of values for styles or properties. For example, on d3js.org `getComputedStyle(document.body).length` returns 262. Similarly, `size = 0; for (var property in document.body) ++size` is 222, though if you ignore properties defined on the prototype chain, it is zero. I suppose if you restricted it to only directly-assigned styles and directly-assigned properties it might be more reasonable, but then the problem is it wouldn’t be consistent with the getter mode of _selection_.style (which is returns the computed style) and _selection_.property (which includes inherited properties).
